/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentProgressBar: typeof import('./src/components/AgentProgressBar.vue')['default']
    CardContextMenu: typeof import('./src/components/CardContextMenu.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    ChatPanel: typeof import('./src/components/ChatPanel.vue')['default']
    ColumnEditor: typeof import('./src/components/ColumnEditor.vue')['default']
    ContextGauge: typeof import('./src/components/ContextGauge.vue')['default']
    EditCardDialog: typeof import('./src/components/EditCardDialog.vue')['default']
    GlobalSettings: typeof import('./src/components/GlobalSettings.vue')['default']
    ImportSessionsDialog: typeof import('./src/components/ImportSessionsDialog.vue')['default']
    InputToolbar: typeof import('./src/components/InputToolbar.vue')['default']
    KanbanBoard: typeof import('./src/components/KanbanBoard.vue')['default']
    KanbanCard: typeof import('./src/components/KanbanCard.vue')['default']
    KanbanColumn: typeof import('./src/components/KanbanColumn.vue')['default']
    NewSessionDialog: typeof import('./src/components/NewSessionDialog.vue')['default']
    PipelineEditor: typeof import('./src/components/PipelineEditor.vue')['default']
    ProjectSettings: typeof import('./src/components/ProjectSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionMetrics: typeof import('./src/components/SessionMetrics.vue')['default']
    SlashCommandPalette: typeof import('./src/components/SlashCommandPalette.vue')['default']
    StatusIndicator: typeof import('./src/components/StatusIndicator.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    TaskListDisplay: typeof import('./src/components/TaskListDisplay.vue')['default']
    ToolCallBlock: typeof import('./src/components/ToolCallBlock.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.1_@tiptap+core@3.20.1_@tiptap+pm@3.20.1__@tiptap_bbb7570f7f1af5ce1ab4a985d464db36/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.1_@tiptap+core@3.20.1_@tiptap+pm@3.20.1__@tiptap_bbb7570f7f1af5ce1ab4a985d464db36/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UChatMessages: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.1_@tiptap+core@3.20.1_@tiptap+pm@3.20.1__@tiptap_bbb7570f7f1af5ce1ab4a985d464db36/node_modules/@nuxt/ui/dist/runtime/components/ChatMessages.vue')['default']
    UChatPrompt: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.1_@tiptap+core@3.20.1_@tiptap+pm@3.20.1__@tiptap_bbb7570f7f1af5ce1ab4a985d464db36/node_modules/@nuxt/ui/dist/runtime/components/ChatPrompt.vue')['default']
    UChatPromptSubmit: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.1_@tiptap+core@3.20.1_@tiptap+pm@3.20.1__@tiptap_bbb7570f7f1af5ce1ab4a985d464db36/node_modules/@nuxt/ui/dist/runtime/components/ChatPromptSubmit.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.1_@tiptap+core@3.20.1_@tiptap+pm@3.20.1__@tiptap_bbb7570f7f1af5ce1ab4a985d464db36/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
  }
}
